/**
 * Style-check word/phrase lists, in the spirit of iA Writer's Style Check.
 *
 * Entry syntax follows iA Writer's pattern language: `~~ ~~` marks the
 * deletable sub-span — "combine ~~together~~" matches the whole phrase but
 * strikes only "together", so the strikethrough always reads as "delete
 * exactly this and the sentence still works". Entries without markers strike
 * the whole match (fillers, clichés). Redundancies include generated
 * inflection variants (combines/combined/combining together).
 *
 * Merged from open-source prose-linter data, then curated for low noise:
 * - no-cliches (MIT, github.com/duereg/no-cliches) — cliche phrases
 * - proselint's Garner redundancy data (BSD-3, github.com/amperser/proselint),
 *   whose phrase→replacement pairs also derive the strike spans
 * - hand-picked distinctive entries from wooorm's weasels/hedges (MIT);
 *   generic quantifiers ("many", "few", "about") deliberately excluded
 * See THIRD_PARTY_NOTICES.md at the repo root for license texts.
 *
 * Keep entries lowercase (ASCII apostrophes; the matcher also accepts
 * typographic ones in the document). A phrase must not appear in more than
 * one category (enforced by a unit test) so a hit is never decorated twice.
 */

export const FILLERS: readonly string[] = [
    "a lot",
    "absolutely",
    "actually",
    "and so forth",
    "apparently",
    "arguably",
    "as a matter of fact",
    "at the present time",
    "basically",
    "certainly",
    "clearly",
    "completely",
    "definitely",
    "effectively",
    "essentially",
    "et cetera",
    "evidently",
    "exceedingly",
    "extremely",
    "fairly",
    "for all intents and purposes",
    "for the most part",
    "frankly",
    "generally",
    "generally speaking",
    "honestly",
    "hopefully",
    "i believe",
    "i feel",
    "i think",
    "in a sense",
    "in my opinion",
    "in my view",
    "in order to",
    "in terms of",
    "interestingly",
    "just",
    "kind of",
    "largely",
    "literally",
    "lots of",
    "more or less",
    "mostly",
    "needless to say",
    "obviously",
    "of course",
    "particularly",
    "per se",
    "possibly",
    "practically",
    "presumably",
    "pretty much",
    "probably",
    "quite",
    "rather",
    "really",
    "relatively",
    "remarkably",
    "significantly",
    "simply",
    "slightly",
    "so to speak",
    "somewhat",
    "sort of",
    "substantially",
    "supposedly",
    "surprisingly",
    "to be honest",
    "totally",
    "truly",
    "utterly",
    "very",
    "virtually",
    "you know",
];

export const REDUNDANCIES: readonly string[] = [
    "accused of a charge",
    "adequate ~~enough~~",
    "approximately ~~about~~",
    "bivouac ~~camp~~",
    "blend ~~together~~",
    "blended ~~together~~",
    "blending ~~together~~",
    "blends ~~together~~",
    "but ~~nevertheless~~",
    "circumstances surrounding",
    "close ~~proximity~~",
    "collaborate ~~together~~",
    "collaborated ~~together~~",
    "collaborates ~~together~~",
    "collaborating ~~together~~",
    "collocated ~~together~~",
    "combine ~~together~~",
    "combined ~~together~~",
    "combines ~~together~~",
    "combining ~~together~~",
    "connect ~~together~~",
    "connected ~~together~~",
    "connecting ~~together~~",
    "connects ~~together~~",
    "consensus ~~of opinion~~",
    "consolidate ~~together~~",
    "consolidated ~~together~~",
    "consolidates ~~together~~",
    "consolidating ~~together~~",
    "couple ~~together~~",
    "coupled ~~together~~",
    "couples ~~together~~",
    "coupling ~~together~~",
    "each ~~and every~~",
    "emptied ~~out~~",
    "empty ~~out~~",
    "emptying ~~out~~",
    "emptys ~~out~~",
    "few ~~in number~~",
    "first ~~and foremost~~",
    "follow ~~after~~",
    "followed ~~after~~",
    "following ~~after~~",
    "follows ~~after~~",
    "founding forefathers",
    "free ~~and gratis~~",
    "free ~~gratis~~",
    "interact ~~with each other~~",
    "join ~~together~~",
    "joinned ~~together~~",
    "joinning ~~together~~",
    "joins ~~together~~",
    "large ~~in size~~",
    "large-size",
    "meld ~~together~~",
    "melded ~~together~~",
    "melding ~~together~~",
    "melds ~~together~~",
    "merge ~~together~~",
    "merged ~~together~~",
    "merges ~~together~~",
    "merging ~~together~~",
    "mingle ~~together~~",
    "mingled ~~together~~",
    "mingles ~~together~~",
    "mingling ~~together~~",
    "mix ~~together~~",
    "mixed ~~together~~",
    "mixing ~~together~~",
    "mixs ~~together~~",
    "mutual feelings ~~for eachother~~",
    "mutual respect ~~for each other~~",
    "native-born citizen",
    "pause ~~for a moment~~",
    "period ~~of time~~",
    "plan ~~ahead~~",
    "planned ~~ahead~~",
    "planning ~~ahead~~",
    "plans ~~ahead~~",
    "point ~~in time~~",
    "pooled ~~together~~",
    "postpone ~~until later~~",
    "postponed ~~until later~~",
    "postpones ~~until later~~",
    "postponing ~~until later~~",
    "potable ~~drinking~~ water",
    "reason ~~why~~",
    "reasons ~~why~~",
    "reelected ~~for another term~~",
    "refer ~~back~~",
    "refered ~~back~~",
    "refering ~~back~~",
    "refers ~~back~~",
    "regress ~~back~~",
    "regressed ~~back~~",
    "regressing ~~back~~",
    "regresss ~~back~~",
    "repaied them ~~back~~",
    "repaied ~~back~~",
    "repay them ~~back~~",
    "repay ~~back~~",
    "repaying them ~~back~~",
    "repaying ~~back~~",
    "repays them ~~back~~",
    "repays ~~back~~",
    "repeat ~~again~~",
    "repeat ~~back~~",
    "repeat ~~the same~~",
    "repeated ~~the same~~",
    "repeats ~~again~~",
    "repeats ~~back~~",
    "repeats ~~the same~~",
    "repeatted ~~again~~",
    "repeatted ~~back~~",
    "repeatted ~~the same~~",
    "repeatting ~~again~~",
    "repeatting ~~back~~",
    "repeatting ~~the same~~",
    "retiracy",
    "retiral",
    "retreat ~~back~~",
    "retreats ~~back~~",
    "retreatted ~~back~~",
    "retreatting ~~back~~",
    "return ~~back~~",
    "returned ~~back~~",
    "returning ~~back~~",
    "returns ~~back~~",
    "revert ~~back~~",
    "reverted ~~back~~",
    "reverting ~~back~~",
    "reverts ~~back~~",
    "self-admitted",
    "self-complacent",
    "self-confessed",
    "small ~~in size~~",
    "software ~~program~~",
    "surrounded ~~on all sides~~",
    "the ~~whole entire~~ nation",
    "throughout the ~~entire~~",
    "timpani ~~drum~~",
    "various ~~different~~",
    "visible ~~to the eye~~",
    "whether ~~or not~~",
    "while ~~at the same time~~",
    "~~absolutely~~ essential",
    "~~absolute~~ necessity",
    "~~actual~~ fact",
    "~~added~~ bonus",
    "~~added~~ bonuses",
    "~~advance~~ planning",
    "~~advance~~ warning",
    "~~basic~~ fundamentals",
    "~~blatantly~~ obvious",
    "~~brief~~ moment",
    "~~brief~~ respite",
    "~~closely~~ scrutinize",
    "~~completely~~ eliminate",
    "~~completely~~ full",
    "~~current~~ status quo",
    "~~directly~~ antithetical",
    "~~end~~ result",
    "~~end~~ results",
    "~~entirely~~ eliminate",
    "~~exact~~ same",
    "~~fellow~~ collaborator",
    "~~fellow~~ collaborators",
    "~~fellow~~ colleagues",
    "~~final~~ outcome",
    "~~final~~ outcomes",
    "~~former~~ alumnus",
    "~~former~~ veteran",
    "~~free~~ gift",
    "~~free~~ gifts",
    "~~future~~ forecast",
    "~~future~~ plans",
    "~~general~~ public",
    "~~joint~~ collaboration",
    "~~most~~ especially",
    "~~mutually~~ contradictory",
    "~~mutual~~ agreement",
    "~~mutual~~ cooperation",
    "~~new~~ innovation",
    "~~new~~ innovations",
    "~~new~~ recruit",
    "~~pair of~~ twins",
    "~~past~~ experience",
    "~~past~~ experiences",
    "~~past~~ history",
    "~~personal~~ opinion",
    "~~personal~~ opinions",
    "~~professional~~ vocation",
    "~~serious~~ crisis",
    "~~still~~ continues to",
    "~~sum~~ total",
    "~~surrounding~~ circumstances",
    "~~sworn~~ affidavit",
    "~~temporary~~ bivouac",
    "~~temporary~~ reprieve",
    "~~true~~ fact",
    "~~true~~ facts",
    "~~unexpected~~ surprise",
    "~~unexpected~~ surprises",
    "~~unfilled~~ vacancy",
    "~~usual~~ custom",
];

export const CLICHES: readonly string[] = [
    "a chip off the old block",
    "a clean slate",
    "a dark and stormy night",
    "a far cry",
    "a fine kettle of fish",
    "a loose cannon",
    "a penny saved is a penny earned",
    "a tough row to hoe",
    "a word to the wise",
    "ace in the hole",
    "acid test",
    "add insult to injury",
    "against all odds",
    "air your dirty laundry",
    "all fun and games",
    "all in a day's work",
    "all talk, no action",
    "all thumbs",
    "all your eggs in one basket",
    "all's fair in love and war",
    "all's well that ends well",
    "almighty dollar",
    "american as apple pie",
    "an axe to grind",
    "another day, another dollar",
    "armed to the teeth",
    "as luck would have it",
    "as old as time",
    "as the crow flies",
    "at loose ends",
    "at my wits end",
    "at the end of the day",
    "avoid like the plague",
    "babe in the woods",
    "back against the wall",
    "back in the saddle",
    "back to basics",
    "back to square one",
    "back to the drawing board",
    "bad to the bone",
    "badge of honor",
    "bald faced liar",
    "ballpark figure",
    "banging your head against a brick wall",
    "baptism by fire",
    "barking up the wrong tree",
    "bat out of hell",
    "be all and end all",
    "beat a dead horse",
    "beat around the bush",
    "been there, done that",
    "beggars can't be choosers",
    "behind the eight ball",
    "bend over backwards",
    "benefit of the doubt",
    "bent out of shape",
    "best of both worlds",
    "best thing since sliced bread",
    "bet your bottom dollar",
    "better half",
    "better late than never",
    "better mousetrap",
    "better safe than sorry",
    "between a rock and a hard place",
    "beyond a shadow of a doubt",
    "beyond the pale",
    "bide your time",
    "big as life",
    "big cheese",
    "big fish in a small pond",
    "big man on campus",
    "bigger they are the harder they fall",
    "bird in the hand",
    "bird's eye view",
    "birds and the bees",
    "birds of a feather flock together",
    "bit the hand that feeds you",
    "bite the bullet",
    "bite the dust",
    "bitten off more than he can chew",
    "black as coal",
    "black as pitch",
    "black as the ace of spades",
    "blast from the past",
    "bleeding heart",
    "blessing in disguise",
    "blind ambition",
    "blind as a bat",
    "blind leading the blind",
    "blood is thicker than water",
    "blood sweat and tears",
    "blow off steam",
    "blow your own horn",
    "blushing bride",
    "boils down to",
    "bolt from the blue",
    "bone to pick",
    "bored stiff",
    "bored to tears",
    "bottomless pit",
    "boys will be boys",
    "bright and early",
    "brings home the bacon",
    "broad across the beam",
    "broken record",
    "brought back to reality",
    "bull by the horns",
    "bull in a china shop",
    "burn the midnight oil",
    "burning question",
    "burning the candle at both ends",
    "burst your bubble",
    "bury the hatchet",
    "busy as a bee",
    "by hook or by crook",
    "call a spade a spade",
    "called onto the carpet",
    "calm before the storm",
    "can of worms",
    "can't cut the mustard",
    "can't hold a candle to",
    "case of mistaken identity",
    "cat got your tongue",
    "cat's meow",
    "caught in the crossfire",
    "caught red-handed",
    "checkered past",
    "chomping at the bit",
    "cleanliness is next to godliness",
    "clear as a bell",
    "clear as mud",
    "close to the vest",
    "cock and bull story",
    "cold shoulder",
    "come full circle",
    "come hell or high water",
    "cool as a cucumber",
    "cool, calm, and collected",
    "cost a king's ransom",
    "count your blessings",
    "crack of dawn",
    "crash course",
    "cream of the crop",
    "creature comforts",
    "cross that bridge when you come to it",
    "crushing blow",
    "cry like a baby",
    "cry me a river",
    "cry over spilt milk",
    "crystal clear",
    "curiosity killed the cat",
    "cut and dried",
    "cut corners",
    "cut through the red tape",
    "cut to the chase",
    "cute as a bugs ear",
    "cute as a button",
    "cute as a puppy",
    "cuts to the quick",
    "dark before the dawn",
    "day in, day out",
    "dead as a doornail",
    "devil is in the details",
    "diamond in the rough",
    "dime a dozen",
    "divide and conquer",
    "dog and pony show",
    "dog days",
    "dog eat dog",
    "dog tired",
    "don't burn your bridges",
    "don't count your chickens",
    "don't look a gift horse in the mouth",
    "don't rock the boat",
    "don't step on anyone's toes",
    "don't take any wooden nickels",
    "down and out",
    "down at the heels",
    "down in the dumps",
    "down the hatch",
    "down to earth",
    "draw the line",
    "dressed to kill",
    "dressed to the nines",
    "drives me up the wall",
    "dull as dishwater",
    "dyed in the wool",
    "eagle eye",
    "ear to the ground",
    "early bird catches the worm",
    "easier said than done",
    "easy as pie",
    "eat your heart out",
    "eat your words",
    "eleventh hour",
    "even the playing field",
    "every dog has its day",
    "every fiber of my being",
    "everything but the kitchen sink",
    "eye for an eye",
    "face the music",
    "facts of life",
    "fair weather friend",
    "fall by the wayside",
    "fall through the cracks",
    "fan the flames",
    "feast or famine",
    "feather your nest",
    "feathered friends",
    "few and far between",
    "fifteen minutes of fame",
    "filthy vermin",
    "fine kettle of fish",
    "fish out of water",
    "fishing for a compliment",
    "fit as a fiddle",
    "fit the bill",
    "fit to be tied",
    "flash in the pan",
    "flat as a pancake",
    "flip your lid",
    "flog a dead horse",
    "fly by night",
    "fly the coop",
    "follow your heart",
    "food for thought",
    "for the birds",
    "for what it's worth",
    "force of nature",
    "force to be reckoned with",
    "forgive and forget",
    "fox in the henhouse",
    "free and easy",
    "free as a bird",
    "fresh as a daisy",
    "full steam ahead",
    "fun in the sun",
    "garbage in, garbage out",
    "gentle as a lamb",
    "get a kick out of",
    "get a leg up",
    "get down and dirty",
    "get the ball rolling",
    "get the lead out",
    "get to the bottom of",
    "get your feet wet",
    "gets my goat",
    "gilding the lily",
    "give and take",
    "go against the grain",
    "go at it tooth and nail",
    "go for broke",
    "go him one better",
    "go the extra mile",
    "go with the flow",
    "goes without saying",
    "good as gold",
    "good deed for the day",
    "good things come to those who wait",
    "good time was had by all",
    "good times were had by all",
    "grain of salt",
    "greased lightning",
    "greek to me",
    "green thumb",
    "green-eyed monster",
    "grist for the mill",
    "growing like a weed",
    "hair of the dog",
    "hand to mouth",
    "happy as a clam",
    "happy as a lark",
    "hasn't a clue",
    "have a nice day",
    "have high hopes",
    "have the last laugh",
    "haven't got a row to hoe",
    "head honcho",
    "head over heels",
    "hear a pin drop",
    "heard it through the grapevine",
    "heart's content",
    "heavy as lead",
    "hem and haw",
    "high and dry",
    "high and mighty",
    "high as a kite",
    "hit paydirt",
    "hold your head up high",
    "hold your horses",
    "hold your own",
    "hold your tongue",
    "honest as the day is long",
    "horns of a dilemma",
    "horse of a different color",
    "hot under the collar",
    "hour of need",
    "i beg to differ",
    "icing on the cake",
    "if the shoe fits",
    "if the shoe were on the other foot",
    "in a jam",
    "in a jiffy",
    "in a nutshell",
    "in a pig's eye",
    "in a pinch",
    "in a word",
    "in hot water",
    "in the final analysis",
    "in the gutter",
    "in the nick of time",
    "in the thick of it",
    "in your dreams",
    "it ain't over till the fat lady sings",
    "it goes without saying",
    "it takes all kinds",
    "it takes one to know one",
    "it's a small world",
    "it's only a matter of time",
    "ivory tower",
    "jack of all trades",
    "jockey for position",
    "jog your memory",
    "joined at the hip",
    "judge a book by its cover",
    "jump down your throat",
    "jump in with both feet",
    "jump on the bandwagon",
    "jump the gun",
    "jump to conclusions",
    "just a hop, skip, and a jump",
    "just the ticket",
    "justice is blind",
    "keep a stiff upper lip",
    "keep an eye on",
    "keep it simple, stupid",
    "keep the home fires burning",
    "keep up with the joneses",
    "keep your chin up",
    "keep your fingers crossed",
    "kick the bucket",
    "kick up your heels",
    "kick your feet up",
    "kid in a candy store",
    "kill two birds with one stone",
    "kiss of death",
    "knock it out of the park",
    "knock on wood",
    "knock your socks off",
    "know him from adam",
    "know the ropes",
    "know the score",
    "knuckle down",
    "knuckle sandwich",
    "knuckle under",
    "labor of love",
    "ladder of success",
    "land on your feet",
    "lap of luxury",
    "last but not least",
    "last hurrah",
    "last-ditch effort",
    "law of the jungle",
    "law of the land",
    "lay down the law",
    "leaps and bounds",
    "let sleeping dogs lie",
    "let the cat out of the bag",
    "let the good times roll",
    "let your hair down",
    "let's talk turkey",
    "letter perfect",
    "level playing field",
    "lick your wounds",
    "lies like a rug",
    "life's a bitch",
    "life's a grind",
    "light at the end of the tunnel",
    "lighter than a feather",
    "lighter than air",
    "like clockwork",
    "like father like son",
    "like taking candy from a baby",
    "like the plague",
    "like there's no tomorrow",
    "lion's share",
    "live and learn",
    "live and let live",
    "long and short of it",
    "long lost love",
    "look before you leap",
    "look down your nose",
    "look what the cat dragged in",
    "looking a gift horse in the mouth",
    "looks like death warmed over",
    "loose cannon",
    "lose your head",
    "lose your temper",
    "loud as a horn",
    "lounge lizard",
    "loved and lost",
    "low man on the totem pole",
    "low-hanging fruit",
    "luck of the draw",
    "luck of the irish",
    "make hay while the sun shines",
    "make money hand over fist",
    "make my day",
    "make the best of a bad situation",
    "make the best of it",
    "make your blood boil",
    "man of few words",
    "man's best friend",
    "mark my words",
    "meaningful dialogue",
    "method to the madness",
    "missed the boat on that one",
    "moment in the sun",
    "moment of glory",
    "moment of truth",
    "money to burn",
    "more power to you",
    "more than one way to skin a cat",
    "movers and shakers",
    "moving experience",
    "moving forward",
    "naked as a jaybird",
    "naked truth",
    "neat as a pin",
    "needle in a haystack",
    "neither here nor there",
    "never look back",
    "never say never",
    "nip and tuck",
    "nip it in the bud",
    "no guts, no glory",
    "no love lost",
    "no pain, no gain",
    "no skin off my back",
    "no stone unturned",
    "no time like the present",
    "no use crying over spilled milk",
    "nose to the grindstone",
    "not a hope in hell",
    "not a minute's peace",
    "not in my backyard",
    "not playing with a full deck",
    "not the end of the world",
    "not written in stone",
    "nothing to sneeze at",
    "nothing ventured nothing gained",
    "now we're cooking",
    "off the top of my head",
    "off the wagon",
    "off the wall",
    "old hat",
    "older and wiser",
    "older than dirt",
    "older than methuselah",
    "on a roll",
    "on cloud nine",
    "on pins and needles",
    "on the bandwagon",
    "on the money",
    "on the nose",
    "on the rocks",
    "on the same page",
    "on the spot",
    "on the tip of my tongue",
    "on the wagon",
    "on thin ice",
    "once bitten, twice shy",
    "once in a blue moon",
    "one bad apple doesn't spoil the bushel",
    "one born every minute",
    "one brick short",
    "one foot in the grave",
    "one in a million",
    "one red cent",
    "only game in town",
    "only time will tell",
    "open a can of worms",
    "open and shut case",
    "open the flood gates",
    "opportunity doesn't knock twice",
    "out of pocket",
    "out of sight, out of mind",
    "out of the box",
    "out of the frying pan into the fire",
    "out of the woods",
    "out on a limb",
    "over a barrel",
    "over the hump",
    "pain and suffering",
    "pain in the",
    "panic button",
    "par for the course",
    "paradigm shift",
    "part and parcel",
    "party pooper",
    "pass the buck",
    "patience is a virtue",
    "pay through the nose",
    "penny pincher",
    "perfect storm",
    "piece of cake",
    "pig in a poke",
    "pile it on",
    "pillar of the community",
    "pin your hopes on",
    "pitter patter of little feet",
    "plain and simple",
    "plain as day",
    "plain as the nose on your face",
    "play by the rules",
    "play your cards right",
    "playing the field",
    "playing with fire",
    "pleased as punch",
    "plenty of fish in the sea",
    "point with pride",
    "poor as a church mouse",
    "pot calling the kettle black",
    "pretty as a picture",
    "pull a fast one",
    "pull your punches",
    "pulling your leg",
    "pure as the driven snow",
    "push the envelope",
    "put it in a nutshell",
    "put one over on you",
    "put the cart before the horse",
    "put the pedal to the metal",
    "put your best foot forward",
    "put your foot down",
    "quick as a bunny",
    "quick as a lick",
    "quick as a wink",
    "quick as lightning",
    "quiet as a dormouse",
    "rags to riches",
    "raining buckets",
    "raining cats and dogs",
    "rank and file",
    "rat race",
    "read between the lines",
    "reap what you sow",
    "red as a beet",
    "red herring",
    "reinvent the wheel",
    "rich and famous",
    "rings a bell",
    "ripe old age",
    "ripped me off",
    "rise and shine",
    "road to hell is paved with good intentions",
    "rob peter to pay paul",
    "roll over in the grave",
    "rub the wrong way",
    "ruled the roost",
    "running in circles",
    "sad but true",
    "sadder but wiser",
    "salt of the earth",
    "scared stiff",
    "scared to death",
    "sealed with a kiss",
    "second to none",
    "see eye to eye",
    "seen the light",
    "seize the day",
    "set the record straight",
    "set the world on fire",
    "set your teeth on edge",
    "sharp as a tack",
    "shoot for the moon",
    "shoot the breeze",
    "shot in the dark",
    "shoulder to the wheel",
    "sick as a dog",
    "sigh of relief",
    "signed, sealed, and delivered",
    "silver lining",
    "sink or swim",
    "six of one, half a dozen of another",
    "skating on thin ice",
    "slept like a log",
    "slinging mud",
    "slippery as an eel",
    "slow as molasses",
    "smart as a whip",
    "smooth as a baby's bottom",
    "sneak peek",
    "sneaking suspicion",
    "snug as a bug in a rug",
    "sow wild oats",
    "spare the rod, spoil the child",
    "speak of the devil",
    "spilled the beans",
    "spinning your wheels",
    "spitting image of",
    "spoke with relish",
    "spread like wildfire",
    "spring to life",
    "squeaky wheel gets the grease",
    "stands out like a sore thumb",
    "start from scratch",
    "stick in the mud",
    "still waters run deep",
    "stitch in time",
    "stop and smell the roses",
    "straight as an arrow",
    "straw that broke the camel's back",
    "strong as an ox",
    "stubborn as a mule",
    "stuff that dreams are made of",
    "stuffed shirt",
    "sweating blood",
    "sweating bullets",
    "take a load off",
    "take it to the next level",
    "take one for the team",
    "take the bait",
    "take the bull by the horns",
    "take the plunge",
    "takes one to know one",
    "takes two to tango",
    "the bottom line",
    "the fact of the matter",
    "the more the merrier",
    "the real deal",
    "the real mccoy",
    "the red carpet treatment",
    "the same old story",
    "there is no accounting for taste",
    "thick as a brick",
    "thick as thieves",
    "thin as a rail",
    "think outside of the box",
    "think outside the box",
    "third time's the charm",
    "this day and age",
    "this hurts me worse than it hurts you",
    "this point in time",
    "three sheets to the wind",
    "through thick and thin",
    "throw in the towel",
    "tie one on",
    "tighter than a drum",
    "time and time again",
    "time is of the essence",
    "tip of the iceberg",
    "tired but happy",
    "to coin a phrase",
    "to each his own",
    "to make a long story short",
    "to the best of my knowledge",
    "toe the line",
    "tongue in cheek",
    "too good to be true",
    "too hot to handle",
    "too numerous to mention",
    "touch with a ten foot pole",
    "tough as nails",
    "trial and error",
    "trials and tribulations",
    "tried and true",
    "trip down memory lane",
    "twist of fate",
    "two cents worth",
    "two peas in a pod",
    "ugly as sin",
    "under the counter",
    "under the gun",
    "under the same roof",
    "under the weather",
    "until the cows come home",
    "unvarnished truth",
    "up in the air",
    "up the creek",
    "uphill battle",
    "upper crust",
    "upset the applecart",
    "vain attempt",
    "vain effort",
    "vanquish the enemy",
    "vested interest",
    "waiting for the other shoe to drop",
    "wakeup call",
    "warm welcome",
    "watch your p's and q's",
    "watch your tongue",
    "watching the clock",
    "water under the bridge",
    "weather the storm",
    "weed them out",
    "week of sundays",
    "went belly up",
    "wet behind the ears",
    "what goes around comes around",
    "what you see is what you get",
    "when all is said and done",
    "when it rains, it pours",
    "when push comes to shove",
    "when the cat's away",
    "when the going gets tough, the tough get going",
    "white as a sheet",
    "whole ball of wax",
    "whole hog",
    "whole nine yards",
    "wild goose chase",
    "will wonders never cease?",
    "win-win situation",
    "wisdom of the ages",
    "wise as an owl",
    "wolf at the door",
    "words fail me",
    "work like a dog",
    "world weary",
    "worst nightmare",
    "worth its weight in gold",
    "writing on the wall",
    "wrong side of the bed",
    "yanking your chain",
    "yappy as a dog",
    "years young",
    "you are what you eat",
    "you can run but you can't hide",
    "you only live once",
    "you're the boss",
    "young and foolish",
    "young and vibrant",
];
