/**
 * Style-check word/phrase lists, in the spirit of iA Writer's Style Check.
 *
 * Curated from open-source prose linters: write-good (MIT), proselint (BSD),
 * and the retext plugin data (MIT). Each entry is matched case-insensitively
 * at word boundaries; multi-word phrases match across any run of whitespace.
 *
 * Keep entries lowercase. A phrase must not appear in more than one category
 * (enforced by a unit test) so a hit is never decorated twice.
 */

export const FILLERS: readonly string[] = [
    "absolutely",
    "actually",
    "arguably",
    "as a matter of fact",
    "at the present time",
    "basically",
    "certainly",
    "clearly",
    "completely",
    "definitely",
    "essentially",
    "extremely",
    "fairly",
    "for all intents and purposes",
    "for the most part",
    "frankly",
    "generally speaking",
    "honestly",
    "i believe",
    "i feel",
    "i think",
    "in a sense",
    "in my opinion",
    "in order to",
    "in terms of",
    "just",
    "kind of",
    "literally",
    "needless to say",
    "obviously",
    "of course",
    "particularly",
    "per se",
    "possibly",
    "pretty much",
    "probably",
    "quite",
    "rather",
    "really",
    "simply",
    "slightly",
    "so to speak",
    "somewhat",
    "sort of",
    "to be honest",
    "totally",
    "truly",
    "utterly",
    "very",
    "virtually",
    "you know",
];

export const REDUNDANCIES: readonly string[] = [
    "absolutely essential",
    "added bonus",
    "advance planning",
    "advance warning",
    "basic fundamentals",
    "blend together",
    "brief moment",
    "close proximity",
    "collaborate together",
    "combine together",
    "completely eliminate",
    "consensus of opinion",
    "current status quo",
    "each and every",
    "empty out",
    "end result",
    "entirely eliminate",
    "exact same",
    "few in number",
    "final outcome",
    "first and foremost",
    "follow after",
    "free gift",
    "future plans",
    "general public",
    "join together",
    "joint collaboration",
    "large in size",
    "merge together",
    "mutual cooperation",
    "new innovation",
    "past experience",
    "past history",
    "period of time",
    "personal opinion",
    "plan ahead",
    "point in time",
    "postpone until later",
    "reason why",
    "refer back",
    "repeat again",
    "revert back",
    "small in size",
    "sum total",
    "surrounded on all sides",
    "true fact",
    "unexpected surprise",
    "usual custom",
    "whether or not",
];

export const CLICHES: readonly string[] = [
    "against all odds",
    "at the end of the day",
    "back to basics",
    "back to square one",
    "ballpark figure",
    "beat around the bush",
    "benefit of the doubt",
    "best of both worlds",
    "better late than never",
    "between a rock and a hard place",
    "beyond a shadow of a doubt",
    "bite the bullet",
    "calm before the storm",
    "come full circle",
    "cream of the crop",
    "crystal clear",
    "cut corners",
    "cut to the chase",
    "diamond in the rough",
    "easier said than done",
    "everything but the kitchen sink",
    "fall through the cracks",
    "few and far between",
    "fit as a fiddle",
    "food for thought",
    "get the ball rolling",
    "go the extra mile",
    "grain of salt",
    "in a nutshell",
    "in the final analysis",
    "in the nick of time",
    "it goes without saying",
    "last but not least",
    "level playing field",
    "light at the end of the tunnel",
    "low-hanging fruit",
    "method to the madness",
    "moving forward",
    "needle in a haystack",
    "nip it in the bud",
    "no stone unturned",
    "on the same page",
    "once in a blue moon",
    "only time will tell",
    "out of the box",
    "par for the course",
    "paradigm shift",
    "part and parcel",
    "piece of cake",
    "plain and simple",
    "push the envelope",
    "read between the lines",
    "silver lining",
    "sneak peek",
    "take it to the next level",
    "the bottom line",
    "the fact of the matter",
    "think outside the box",
    "tip of the iceberg",
    "tried and true",
    "up in the air",
    "when all is said and done",
    "when push comes to shove",
    "win-win situation",
    "writing on the wall",
];
